exclude: ["README.md", "eop-website.iml", "assets-original", "start.sh"]
sass:
  sass_dir: "_scss"
permalink: "pretty"

nav_list:
  - path: index.html
    nav_title: "Being a Monk"
  - path: about/index.html
    nav_title: "Program details"
  - path: media/index.html
    nav_title: "Media"

form_link: https://forms.gle/KxcHbeLUMkrtbVQ68